### ISSUE TITLE
Mouse wheel does not work properly on startup

### ISSUE THREAD

**Issue by Boris-Dimov** [luisgargitter/sdl-projection#3]
When starting up the program, the mouse wheel moves the camera on the X and Y axes, instead of the Z axis. I think it gets registered as the wrong kind of event.

If you click one time, the issue goes away and everything functions normally.

**Comment by luisgargitter** [comment]
the problem was that x and y value were still in v from centering the cube.

**Comment by Boris-Dimov** [comment]
Ah so, ok great, thanks for the fix
